# Generated by Django 6.0.7 on 2026-08-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта")
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
