# Generated by Django 6.0.7 on 2026-08-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = []
