# Generated by Django 6.0.7 on 2026-08-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_sync_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                choices=[
                    ("#FF4500", "Оранжево-красный"),
                    ("#FF8C00", "Тёмно-оранжевый"),
                    ("#8B008B", "Тёмно-фиолетовый"),
                    ("#00008B", "Тёмно-синий"),
                    ("#006400", "Тёмно-зелёный"),
                    ("#8B0000", "Тёмно-красный"),
                    ("#4B0082", "Индиго"),
                    ("#2F4F4F", "Тёмный серо-зелёный"),
                    ("#800000", "Бордовый"),
                    ("#556B2F", "Тёмно-оливковый"),
                ],
                default="#000000",
                max_length=7,
                verbose_name="Цвет",
            ),
        ),
    ]
